package:
  name: fast_dijkstra
  version: 0.1.0

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - fast_dijkstra

about:
  home: https://github.com/chenwei-zhang/fast_dijkstra
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chenwei-zhang
